[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "honi"
version = "0.1.0"
dependencies = []

[project.optional-dependencies]
dev = ["ruff"]

[tool.setuptools.packages.find]
where = ["src"]
